name: Build and Upload ISO

on:
  push:
    tags:
      - 'rocky-*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Rocky Linux ISO
      run: |
        ROCKY_VERSION=${GITHUB_REF#refs/tags/rocky-}
        echo "ROCKY_VERSION=${GITHUB_REF#refs/tags/rocky-}" >> $GITHUB_ENV
        wget -O rocky.iso https://download.rockylinux.org/pub/rocky/${ROCKY_VERSION}/isos/x86_64/Rocky-${ROCKY_VERSION}-x86_64-minimal.iso

    - name: Build container
      run: |
        buildah build -t ns8-boxbuilder .

    - name: Create modified ISO
      run: |
        podman run --rm -it --privileged -v $(pwd):/root localhost/ns8-boxbuilder mkksiso -R "Rocky Linux" "NethServer 8 (Rocky Linux)" --cmdline "inst.ks=https://raw.githubusercontent.com/NethServer/ns8-rocky-iso/refs/heads/main/ks.cfg" rocky.iso ns8-rocky-9.5-x86_64.iso

    - name: Create GitHub Release and Upload ISO
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        name: Rocky Linux ${{ env.ROCKY_VERSION }} for NethServer 8
        files: ns8-rocky-${{ env.ROCKY_VERSION }}-x86_64.iso
